<?php

namespace Encuesta\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatoRepository extends EntityRepository
{
    /*
     * Retorna los candidatos que matchean con el titulo 
     */
    public function getCandidatosPorTitulo($titulo)
    {
        $em = $this->getEntityManager();        
        $sql = 'SELECT c FROM ModeloBundle:Candidato c WHERE ctitulo like :titulo'; 
        $consulta = $em->createQuery($sql);        
        $consulta->setParameter('titulo','%'.$titulo.'%');         
        
        return $consulta->getResult();
    }        
}
