<?php

namespace Encuesta\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository
{
    /*
     * Retorna todos los eventos activos
     */
    public function getEventosActivos()
    {
        $em = $this->getEntityManager();
        //$sql = 'SELECT e FROM ModeloBundle:Evento e WHERE e.fecha_fin >= :fecha and e.activo = 1'; 
        $sql = 'SELECT e FROM ModeloBundle:Evento e WHERE e.activo = 1'; 
        $consulta = $em->createQuery($sql);
	//$consulta->setParameter('fecha', new \DateTime('today'));
        return $consulta->getResult(); 
    }
}
