dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /administracion

homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index, name: '' }
