dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /administracion
    
frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /    

homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index, name: '' }
