jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Encuesta\ModeloBundle\Entity\Usuario: { algorithm: sha512, iterations: 5 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Encuesta\ModeloBundle\Entity\Usuario, property: username }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        dashboard:
            pattern: ^/dashboard
            provider:  usuarios
            anonymous: ~
            form_login:
                login_path: dashboard_login
                check_path: dashboard_login_check
            logout:
                path: dashboard_logout
                target: /dashboard
            remember_me:
                key: encuesta_dashboard
                lifetime: 3600

    access_control:
        - { path: ^/dashboard/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
