jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Encuesta\ModeloBundle\Entity\Usuario: { algorithm: sha512, iterations: 5 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Encuesta\ModeloBundle\Entity\Usuario, property: username }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        dashboard:
            pattern: ^/administracion
            provider:  usuarios
            anonymous: ~
            form_login:
                login_path: dashboard_login
                check_path: dashboard_login_check
            logout:
                path: dashboard_logout
                target: /administracion
            remember_me:
                key: encuesta_dashboard
                lifetime: 3600
        frontend:
            pattern: ^/
            provider:  usuarios
            anonymous: ~
            form_login:
                login_path: frontend_login
                check_path: frontend_login_check
                default_target_path: frontend_homepage
            logout:
                path: frontend_logout
                target: /
            remember_me:
                key: encuesta_frontend
                lifetime: 3600
            #fos_facebook:
                #app_url: "http://apps.facebook.com/appName/"
                #server_url: "http://localhost/facebookApp/"    

    access_control:
        - { path: ^/administracion/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administracion, roles: ROLE_ADMIN }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_USER] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
