jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        dashboard:
            pattern: ^/administracion
            provider:  in_memory
            anonymous: ~
            form_login:
                login_path: dashboard_login
                check_path: dashboard_login_check
            logout:
                path: dashboard_logout
                target: /administracion
            remember_me:
                key: topvoting_dashboard
                lifetime: 3600

    access_control:
        - { path: ^/administracion/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administracion, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
