frontend_login:
    pattern:  /{culture}/login
    defaults: { _controller: FrontendBundle:Usuario:login, culture: es}

frontend_login_check:
    pattern:  /login_check

frontend_logout:
    pattern:  /logout
    
frontend_registro:
    pattern:  /{culture}/registro
    defaults: { _controller: FrontendBundle:Usuario:registro , culture: es}    

frontend_homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index, culture: es }
