frontend_login:
    pattern:  /{culture}/login
    defaults: { _controller: FrontendBundle:Usuario:login, culture: es}

frontend_login_check:
    pattern:  /login_check

frontend_logout:
    pattern:  /logout
    
frontend_registro:
    pattern:  /{culture}/registro
    defaults: { _controller: FrontendBundle:Usuario:registro , culture: es}  
    
frontend_activacion:
    pattern:  /{culture}/usuarios/activacion/{codigo}
    defaults: { _controller: FrontendBundle:Usuario:activacion , culture: es}   
    
frontend_perfil:
    pattern:  /{culture}/perfil
    defaults: { _controller: FrontendBundle:Usuario:perfil , culture: es}      

frontend_votaciones:
    pattern:  /{culture}/votaciones
    defaults: { _controller: FrontendBundle:Votacion:votaciones , culture: es}
    
frontend_agregar_candidato:
    pattern:  /{culture}/votaciones/agregar/candidato
    defaults: { _controller: FrontendBundle:Votacion:agregarCandidato , culture: es}  
    
frontend_cambiar_estado_evento:
    pattern:  /{culture}/evento/cambiar/estado
    defaults: { _controller: FrontendBundle:Votacion:modificarEstadoVotacion , culture: es}     

frontend_homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index, culture: es }
