frontend_login:
    pattern:  /{_locale}/login
    defaults: { _controller: FrontendBundle:Usuario:login, _locale: es}

frontend_login_check:
    pattern:  /login_check

frontend_logout:
    pattern:  /logout
    
frontend_registro:
    pattern:  /{_locale}/registro
    defaults: { _controller: FrontendBundle:Usuario:registro , _locale: es}  
    
frontend_activacion:
    pattern:  /{_locale}/usuarios/activacion/{codigo}
    defaults: { _controller: FrontendBundle:Usuario:activacion , _locale: es}   
    
frontend_perfil:
    pattern:  /{_locale}/perfil
    defaults: { _controller: FrontendBundle:Usuario:perfil , _locale: es}      

frontend_votaciones:
    pattern:  /{_locale}/votaciones
    defaults: { _controller: FrontendBundle:Votacion:votaciones , _locale: es}
    
frontend_agregar_candidato:
    pattern:  /{_locale}/votaciones/agregar/candidato
    defaults: { _controller: FrontendBundle:Votacion:agregarCandidato , _locale: es}  
    
frontend_cambiar_estado_evento:
    pattern:  /{_locale}/evento/cambiar/estado
    defaults: { _controller: FrontendBundle:Votacion:modificarEstadoVotacion , _locale: es}    
    
frontend_evento_votar:
    pattern:  /{_locale}/evento/votar
    defaults: { _controller: FrontendBundle:Votacion:votar , _locale: es}       
    
frontend_evento:
    pattern:  /{_locale}/evento
    defaults: { _controller: FrontendBundle:Votacion:evento , _locale: es} 

frontend_homepage:
    pattern:  /{_locale}
    defaults: { _controller: FrontendBundle:Default:index, _locale: es }
